name: Continuous Deployment
on:
  push:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: self-hosted
    container: ubuntu:14.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install php5
        run: |
          sudo apt update && sudo apt install php5 -yqq

      - name: Run index.php
        run: |
          php index.php

  deploy:
    runs-on: self-hosted
    container: ubuntu:14.04
    steps:
      - uses: actions/checkout@master
      - name: SCP file to /tmp path
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PUBLIC_IP_VM }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "index.php"
          target: "/tmp"

      - name: Execute php script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PUBLIC_IP_VM }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: killall -9 php ; cd /tmp ; php -S 0:8000 &>/dev/null & exit
