name: Continuous Integration
on:
  push:
    branches-ignore:
      - master
      - main
  pull_request:
    branches-ignore:
      - master
      - main

jobs:
  test:
    runs-on: self-hosted
    container: ubuntu:14.04
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install php5
        run: |
          sudo apt update && sudo apt install php5 -yqq

      - name: Run index.php
        run: |
          php index.php
      
      